version: 2
jobs:
  build:
    working_directory: ~/learning-site
    docker:
      - image: circleci/node:10.9.0-stretch
    steps:
      - run:
          name: Enable Apache CouchDB package repository
          command: |
            (distribution=stretch; echo "deb https://apache.bintray.com/couchdb-deb ${distribution} main") \
            | sudo tee -a /etc/apt/sources.list
      - run:
          name: Install CouchDB package repository key
          command: |
            curl -L https://couchdb.apache.org/repo/bintray-pubkey.asc \
            | sudo apt-key add -
      - run:
          name: Install CouchDB
          command: |
            sudo apt-get install apt-transport-https
            sudo apt-get update
            echo "couchdb couchdb/mode select none" | sudo debconf-set-selections
            DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes couchdb
      - run:
          name: Start CouchDB
          command: |
            sudo -i -u couchdb /home/couchdb/bin/couchdb
            curl --fail http://localhost:5984/_up
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: run-tests
          command: npm test && npm run test:ui
