version: 2
jobs:
  build:
    working_directory: ~/learning-site
    docker:
      - image: circleci/node:10.9.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: npm install -g npm
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: run-tests
          command: npm test && npm run test:ui
