version: 2
jobs:
  build:
    working_directory: ~/learning-site
    docker:
      - image: circleci/node:10.9.0-stretch
    steps:
      - run:
          name: "Workaround 'invoke-rc.d: policy-rc.d denied execution of start'"
          command: |
            sudo sed -i 's/^exit 101$/exit 0/' /usr/sbin/policy-rc.d
            cat /usr/sbin/policy-rc.d
      - run:
          name: Enable Apache CouchDB package repository
          command: |
            (distribution=stretch; echo "deb https://apache.bintray.com/couchdb-deb ${distribution} main") \
            | sudo tee -a /etc/apt/sources.list
      - run:
          name: Install CouchDB package repository key
          command: |
            curl -L https://couchdb.apache.org/repo/bintray-pubkey.asc \
            | sudo apt-key add -
      - run:
          name: Install CouchDB
          command: |
            sudo apt-get install apt-transport-https
            sudo apt-get update
            echo "couchdb couchdb/mode select none" | sudo debconf-set-selections
            DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes couchdb
      - run:
          name: Ensure CouchDB is started
          command: curl --fail http://localhost:5984/_up
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "learning-site-ui/package.json" }}
            - v1-dependencies-{{ checksum "package.json" }}-
            - v1-dependencies-
      - run:
          name: install-dependencies
          command: npm install && cd learning-site-ui && npm install
      - save_cache:
          paths:
            - node_modules
            - learning-site-ui/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "learning-site-ui/package.json" }}
      - run:
          name: run-tests
          command: npm test && npm run test:ui
